# Generated by Django 3.2 on 2023-11-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/', verbose_name='Фото для превью'),
        ),
    ]
