# Generated by Django 3.2 on 2023-11-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_cource_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/%d', verbose_name='Фото для превью'),
        ),
    ]
