# Generated by Django 3.2 on 2023-11-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='videos.lesson')),
            ],
            options={
                'verbose_name': 'Тест с вопросами',
                'verbose_name_plural': 'Тесты с вопросами',
                'db_table': 'quizes',
                'ordering': ['-created_at'],
            },
        ),
    ]
