# Generated by Django 3.2 on 2023-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок отображения'),
        ),
    ]
